### ISSUE TITLE
rerun unittests on geth

### ISSUE THREAD

**Issue by abbbe** [abbbe/b9labs-eth20-proj2#12]

**Comment by abbbe** [comment]
```$ truffle test --network net24601
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/OwnableKillable.sol...
Compiling ./contracts/Remittance.sol...


  Contract: Remittance
    ✓ cannot send funds to constructor (808ms)
    deployed:
      ✓ sender cannot remit zero amount (25155ms)
      ✓ sender cannot remit to zero recipient address (21130ms)
      ✓ sender cannot reuse OTP (22144ms)
      1) cannot just send funds to the contract
    > No events were emitted
      ✓ contract owner can kill (5031ms)
      2) cannot kill killed contract

    Events emitted during test:
    ---------------------------

    LogKilled()

    ---------------------------
      3) contract non-owner cannot kill
    > No events were emitted
      ✓ cannot send funds with kill()
    revoke:
      ✓ cannot send funds with revoke()
      ✓ sender can revoke an unclaimed remittance, LogRevoke fires (18087ms)
      ✓ sender cannot revoke remittance twice (5026ms)
      ✓ recipient cannot claim revoked remittance (2038ms)
    claim:
      ✓ sender can remit positive amount to non-zero recipient address (32175ms)
      ✓ recipient cannot claim with an incorrect OTP (15091ms)
      ✓ non-recipient cannot claim even with correct OTP (41201ms)
      ✓ cannot send funds with claim()
      ✓ recipient can claim with correct OTP, LogClaim fires (7055ms)
      ✓ recipient cannot claim twice (9054ms)
      ✓ sender cannot revoke claimed remittance (10063ms)


  17 passing (9m)
  3 failing

  1) Contract: Remittance deployed: cannot just send funds to the contract:
     AssertionError: expected -1 to be at least 0
      at Function.assert.isAtLeast (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/chai/lib/chai/interface/assert.js:274:1)
      at test/test_remittance.js:60:21
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  2) Contract: Remittance deployed: cannot kill killed contract:
     AssertionError: expected -1 to be at least 0
      at Function.assert.isAtLeast (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/chai/lib/chai/interface/assert.js:274:1)
      at test/test_remittance.js:77:21
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  3) Contract: Remittance deployed: contract non-owner cannot kill:
     AssertionError: expected -1 to be at least 0
      at Function.assert.isAtLeast (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/chai/lib/chai/interface/assert.js:274:1)
      at test/test_remittance.js:84:21
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by abbbe** [comment]
```diff --git a/test/test_remittance.js b/test/test_remittance.js
index b6f6146..dd1d6a1 100644
--- a/test/test_remittance.js
+++ b/test/test_remittance.js
@@ -57,7 +57,7 @@ contract('Remittance', function (accounts) {
     it("cannot just send funds to the contract", function () {
       return remittance.sendTransaction({ value: 1 }).then(
         () => assert.fail('should not have worked'),
-        e => assert.isAtLeast(e.message.indexOf("VM Exception while processing transaction: revert"), 0)
+        e => console.log(e) //assert.isAtLeast(e.message.indexOf("VM Exception while processing transaction: revert"), 0)
       );
     });
```

results in

```{ Error: Transaction: 0x2eefcf7faab59a9af0260ba3516646465c1e272b7fd97165cf8f49e0d6f93ba4 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.

    at StatusError.ExtendableError (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-error/index.js:10:1)
    at new StatusError (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-contract/statuserror.js:29:1)
    at Object.callback (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:179:1)
    at /Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Transaction: 0x2eefcf7faab59a9af0260ba3516646465c1e272b7fd97165cf8f49e0d6f93ba4 exited with an error (status 0).\nPlease check that the transaction:\n    - satisfies all conditions set by Solidity `require` statements.\n    - does not trigger a Solidity `revert` statement.\n',
  stack: 'Error: Transaction: 0x2eefcf7faab59a9af0260ba3516646465c1e272b7fd97165cf8f49e0d6f93ba4 exited with an error (status 0).\nPlease check that the transaction:\n    - satisfies all conditions set by Solidity `require` statements.\n    - does not trigger a Solidity `revert` statement.\n\n    at StatusError.ExtendableError (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-error/index.js:10:1)\n    at new StatusError (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-contract/statuserror.js:29:1)\n    at Object.callback (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:179:1)\n    at /Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1\n    at /Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1\n    at /Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1\n    at XMLHttpRequest.request.onreadystatechange (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)\n    at XMLHttpRequestEventTarget.dispatchEvent (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)\n    at XMLHttpRequest._setReadyState (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)\n    at XMLHttpRequest._onHttpResponseEnd (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)\n    at IncomingMessage.<anonymous> (/Users/abb/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1055:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  name: 'StatusError',
  tx: '0x2eefcf7faab59a9af0260ba3516646465c1e272b7fd97165cf8f49e0d6f93ba4',
  receipt:
   { blockHash: '0x0e1bef1ffc2b53dc60c0023ae1b68c5b5ce9aa50b4a070baaf6c49c65bce1789',
     blockNumber: 8841,
     contractAddress: null,
     cumulativeGasUsed: 21046,
     from: '0xf23612037a0b33e860ef56b6db496ef6688b955a',
     gasUsed: 21046,
     logs: [],
     logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     status: '0x0',
     to: '0xd1297a8c2246e450889f8f4ba413db4916533ecb',
     transactionHash: '0x2eefcf7faab59a9af0260ba3516646465c1e272b7fd97165cf8f49e0d6f93ba4',
     transactionIndex: 0 } }```
